
package com.bsoft.gwClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BSXmlWsEntryClassServicePortType", targetNamespace = "http://www.bsoft.com.cn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BSXmlWsEntryClassServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.bsoft.gwClient.InvokeResponse
     */
    @WebMethod(action = "http://www.bsoft.com.cn/invoke")
    @WebResult(name = "invokeResponse", targetNamespace = "http://www.bsoft.com.cn", partName = "parameters")
    public InvokeResponse invoke(
        @WebParam(name = "invokeRequest", targetNamespace = "http://www.bsoft.com.cn", partName = "parameters")
        InvokeRequest parameters);

}
