
package com.bsoft.gwClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BSXmlWsEntryClassService", targetNamespace = "http://www.bsoft.com.cn", wsdlLocation = "http://196.168.0.190:9528/hai/WebServiceEntry?wsdl")
public class BSXmlWsEntryClassService
    extends Service
{

    private final static URL BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BSXMLWSENTRYCLASSSERVICE_EXCEPTION;
    private final static QName BSXMLWSENTRYCLASSSERVICE_QNAME = new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://196.168.0.190:9528/hai/WebServiceEntry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION = url;
        BSXMLWSENTRYCLASSSERVICE_EXCEPTION = e;
    }

    public BSXmlWsEntryClassService() {
        super(__getWsdlLocation(), BSXMLWSENTRYCLASSSERVICE_QNAME);
    }

    public BSXmlWsEntryClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSXMLWSENTRYCLASSSERVICE_QNAME, features);
    }

    public BSXmlWsEntryClassService(URL wsdlLocation) {
        super(wsdlLocation, BSXMLWSENTRYCLASSSERVICE_QNAME);
    }

    public BSXmlWsEntryClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSXMLWSENTRYCLASSSERVICE_QNAME, features);
    }

    public BSXmlWsEntryClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSXmlWsEntryClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BSXmlWsEntryClassServicePortType
     */
    @WebEndpoint(name = "BSXmlWsEntryClassServicePort")
    public BSXmlWsEntryClassServicePortType getBSXmlWsEntryClassServicePort() {
        return super.getPort(new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassServicePort"), BSXmlWsEntryClassServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSXmlWsEntryClassServicePortType
     */
    @WebEndpoint(name = "BSXmlWsEntryClassServicePort")
    public BSXmlWsEntryClassServicePortType getBSXmlWsEntryClassServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassServicePort"), BSXmlWsEntryClassServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSXMLWSENTRYCLASSSERVICE_EXCEPTION!= null) {
            throw BSXMLWSENTRYCLASSSERVICE_EXCEPTION;
        }
        return BSXMLWSENTRYCLASSSERVICE_WSDL_LOCATION;
    }

}
